name: proscons
description: Pros and cons app


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  get_it: ^7.2.0
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator: ^1.0.4
  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4


flutter:

  uses-material-design: true




